### ISSUE TITLE
Less margin/padding on smaller screens

### ISSUE THREAD

**Issue by simonw** [simonw/til#80]
Currently:

<img width="600" alt="image" src="https://github.com/simonw/til/assets/9599/0f1ec9a7-01d9-4383-a44f-b4d71df695fc">

I'd like less margin on smaller screens.

**Comment by simonw** [comment]
The padding comes from here: https://github.com/simonw/til/blob/dcdb8aabed967e4ebc17d013fcd9a0cf5b9cc739/templates/til_base.html#L58-L61

**Comment by simonw** [comment]
1em looks better - I'll set that for widths smaller than 600px.

**Comment by simonw** [comment]
```css
@media (max-width: 600px) {
    section.body {
        padding: 0em 1em;
    }
}
```
